Add script and update gitlab-ci to check php 8 compatibility

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -3,47 +3,14 @@ include:
     file: '/templates/main.gitlab-ci.yml'
 
 stages:
-  - coverage and tests
-  - check-php-version
   - check php
+  - check-php-version
+  - coverage and tests
   - releasy-review
   - translations
   - assets
   - build
   - releasy-release
-
-coverage test:
-  image: php:7.2.1
-  stage: coverage and tests
-  cache:
-    key: $CI_COMMIT_REF_SLUG
-    paths:
-      - vendor/
-  before_script:
-    # Install git, the php image doesn't have installed
-    - apt-get update -yqq
-    - apt-get install git -yqq
-
-    # Install Xdebug
-    - pecl install xdebug
-    - docker-php-ext-enable xdebug
-
-    # Install composer version 1
-    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer --version=1.10.16
-
-    # Install all project dependencies
-    - composer install
-  script:
-    - echo 'xdebug.mode=coverage' >> /usr/local/etc/php/php.ini
-    - echo 'error_reporting=22527' > /usr/local/etc/php/conf.d/ci.ini
-    - vendor/bin/phpunit --coverage-text --colors=never
-
-check php version:
-  image: php:8.0-alpine
-  stage: check-php-version
-  script:
-    - sh ci/check_php.sh
-
 
 php cs fixer:
   image: composer:1.9
@@ -51,6 +18,35 @@ php cs fixer:
   script:
     - composer install
     - vendor/bin/php-cs-fixer fix -vvv --dry-run --using-cache=no
+  artifacts:
+    paths:
+      - vendor
+
+check php version:
+  image: php:8.0-alpine
+  stage: check-php-version
+  script:
+    - >
+      RED='\033[0;31m';
+      ORANGE='\033[0;33m';
+      php ci/check_php.php || exit_code=$?;
+      if [ $exit_code -eq 137 ]; then echo -e "\n${ORANGE}WARNING DETECTED!! \n"; exit 126 ; fi;
+      if [ $exit_code -eq 1 ]; then echo -e "\n${RED}ERROR DETECTED!!!\n"; exit 1;
+      elif [ $exit_code -ne 0 ]; then echo -e "\n${RED}FATAL ERROR : SOMETHING UNEXPECTED HAPPENED... EXIT CODE: $exit_code\n"; exit 1; fi;
+  allow_failure:
+    exit_codes: 126
+
+coverage test:
+  image: php:7.2.1
+  stage: coverage and tests
+  before_script:
+    # Install Xdebug
+    - pecl install xdebug
+    - docker-php-ext-enable xdebug
+  script:
+    - echo 'xdebug.mode=coverage' >> /usr/local/etc/php/php.ini
+    - echo 'error_reporting=22527' > /usr/local/etc/php/conf.d/ci.ini
+    - vendor/bin/phpunit --coverage-text --colors=never
 
 check module translations:
   image: php:7.4
@@ -97,6 +93,7 @@ build zip release:
   image: composer:1.9
   stage: build
   before_script:
+    - rm -r ./vendor
     - composer install --no-dev
     - ./ci/copy_translations.sh
     - find ./vendor -type d -exec cp index.php {} \;
@@ -119,6 +116,7 @@ build zip bancontact:
   image: composer:1.9
   stage: build
   before_script:
+    - rm -r ./vendor
     - composer install --no-dev
     - composer require payplug/payplug-php:dev-wip-bancontact --ignore-platform-reqs php
     - ./ci/copy_translations.sh
